version: "3"
services:
    app:
        # image: cc-skill-test-laravel:latest
        image: ghcr.io/theoyrus/cc-be-test:latest
        container_name: app
        restart: unless-stopped
        volumes:
            # - ./storage:/app/storage
            - ./Docker/entrypoint/artisan.sh:/opt/docker/provision/entrypoint.d/artisan.sh
        tty: true
        env_file: .env.production
        depends_on:
            - mariadb
            - cache
        networks:
            - laravel-prod
        ports:
            - "8080:80"

    mariadb:
        container_name: db
        hostname: mariadb
        image: mariadb:10.5.16
        restart: on-failure
        env_file: .env.production
        volumes:
            - data:/var/lib/mysql
            - "./Docker/mariadb/mariadb.cnf:/etc/mysql/mariadb.cnf"
        networks:
            - laravel-prod

    cache:
        image: redis:alpine
        container_name: cache
        restart: unless-stopped
        networks:
            - laravel-prod

#Docker Networks
networks:
    laravel-prod:
        driver: bridge

volumes:
    data:
